# Generated by Django 4.2.1 on 2023-07-17 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_remove_university_project_category_and_more'),
        ('entities', '0002_alter_branch_name_alter_degree_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0002_remove_collegedegree_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('access_url', models.URLField(verbose_name='Access Url')),
                ('report_link', models.CharField(blank=True, max_length=64, null=True, verbose_name='Report Link')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_user_branch', to='entities.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors_college', to='college.college')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_user_degree', to='entities.degree')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_user_state', to='entities.state')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_user_university', to='university.university')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'College Users',
                'verbose_name_plural': 'College Users',
            },
        ),
    ]
