# Generated by Django 4.2.1 on 2023-07-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_alter_collegeusers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeusers',
            name='disable_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
