# Generated by Django 4.2.1 on 2023-07-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_collegeusers_disable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='disable_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
