# Generated by Django 4.2.1 on 2023-09-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_universitycollaboration_universitycms'),
        ('college', '0008_collegecollaboration_collegecms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='university',
        ),
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.ManyToManyField(to='university.university'),
        ),
    ]
