# Generated by Django 4.2.1 on 2023-09-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_remove_college_university_college_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='degree',
        ),
    ]
