# Generated by Django 4.2.1 on 2023-09-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_batches_disable_date'),
        ('college', '0016_alter_collegebatches_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegebatches',
            name='batches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_batches', to='entities.batches'),
        ),
    ]
