# Generated by Django 4.2.1 on 2023-09-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_alter_collegebatches_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegebatches',
            name='college_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_degree_batches', to='college.collegedegree'),
        ),
    ]
