# Generated by Django 4.2.5 on 2023-09-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_batches_disable_date'),
        ('college', '0018_alter_collegebatches_college_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchBatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('batches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_batches', to='entities.batches')),
            ],
            options={
                'verbose_name': 'CollegeBatches',
                'verbose_name_plural': 'College Batches',
            },
        ),
        migrations.CreateModel(
            name='DegreeBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_branch', to='entities.branch')),
                ('college_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_degree_batches', to='college.collegedegree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='college',
            name='branch',
        ),
        migrations.DeleteModel(
            name='CollegeBatches',
        ),
        migrations.AddField(
            model_name='branchbatches',
            name='degree_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_degree_batches', to='college.degreebranch'),
        ),
    ]
