# Generated by Django 4.2.5 on 2023-09-26 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_batches_disable_date'),
        ('college', '0020_alter_degreebranch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchbatches',
            options={'verbose_name': 'Branch Batches', 'verbose_name_plural': 'Branch Batches'},
        ),
        migrations.AlterField(
            model_name='degreebranch',
            name='college_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_degree_branch', to='college.collegedegree'),
        ),
        migrations.AlterUniqueTogether(
            name='branchbatches',
            unique_together={('degree_branch', 'batches')},
        ),
    ]
