# Generated by Django 4.2.5 on 2024-01-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0025_alter_college_name_alter_collegeusers_report_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(error_messages={'unique': 'College name already exists.'}, max_length=240, unique=True, verbose_name='College Name'),
        ),
    ]
