# Generated by Django 4.2.5 on 2024-02-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0026_alter_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeusers',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_user_branch', to='college.degreebranch'),
        ),
        migrations.AlterField(
            model_name='collegeusers',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_user_degree', to='college.collegedegree'),
        ),
    ]
