# Generated by Django 4.2.5 on 2023-10-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_group_of_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tag',
            field=models.CharField(blank=True, choices=[('all_students', 'All Students'), ('group_of_students', 'Group of Students'), ('individual_student', 'Individual Student')], max_length=32, null=True, verbose_name='Notification Tag'),
        ),
    ]
