# Generated by Django 4.2.5 on 2023-10-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='group_of_student',
        ),
    ]
