# Generated by Django 4.2.5 on 2023-10-18 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0005_remove_notification_group_of_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_of_student',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_of_student_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
