# Generated by Django 4.2.5 on 2024-02-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_alter_notification_group_of_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Notification Message'),
        ),
    ]
