repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.0
    hooks:
    - id: black
      exclude: '^.*migrations/.*\.py$'
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        exclude: '^.*migrations/.*\.py$'

        additional_dependencies:
        - black==23.10.0
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: '^.*migrations/.*\.py$'
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: '^.*migrations/.*\.py$'
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.52.0
    hooks:
      - id: eslint
        exclude: '^.*migrations/.*\.py$'