# Generated by Django 4.2.1 on 2023-09-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cron_name', models.CharField(choices=[('discount_start_end_cron', 'discount_start_end_cron'), ('remove_log_of_after_7_days', 'discount_start_end_cron'), ('empty_cart_model', 'discount_start_end_cron'), ('inactive_student_after_1_year', 'discount_start_end_cron')], max_length=100, verbose_name='Cron Name')),
                ('is_error', models.CharField(max_length=1000, verbose_name='Is Error')),
                ('is_cron_complete_successfully', models.BooleanField(verbose_name='Is cron complete successfully')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
