# Generated by Django 4.2.5 on 2023-11-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_logger', '0005_alter_cronlogger_cron_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerErrorHandel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('error_name', models.CharField(max_length=32, verbose_name='500 error')),
                ('error', models.TextField(verbose_name='500 error')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
