# Generated by Django 4.2.5 on 2023-11-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_logger', '0006_servererrorhandel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servererrorhandel',
            name='error',
            field=models.TextField(verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='servererrorhandel',
            name='error_name',
            field=models.CharField(max_length=32, verbose_name='Error Name'),
        ),
    ]
