# Generated by Django 4.2.5 on 2023-12-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_logger', '0007_alter_servererrorhandel_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servererrorhandel',
            name='request_api',
            field=models.TextField(blank=True, null=True, verbose_name='Request API'),
        ),
        migrations.AddField(
            model_name='servererrorhandel',
            name='request_data',
            field=models.TextField(blank=True, null=True, verbose_name='Request Data'),
        ),
        migrations.AddField(
            model_name='servererrorhandel',
            name='request_path',
            field=models.TextField(blank=True, null=True, verbose_name='Request Path'),
        ),
    ]
