# Generated by Django 4.2.1 on 2023-07-12 08:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64, verbose_name='Organization Type')),
                ('address', models.TextField(verbose_name='Address')),
                ('geo_tag', models.CharField(max_length=64, verbose_name='Geo Tag')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(-90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(-180)])),
                ('pan_no', models.CharField(max_length=64, verbose_name='PAN No')),
                ('tan_no', models.CharField(max_length=64, verbose_name='TAN No')),
                ('gstin', models.CharField(max_length=64, verbose_name='GSTIN')),
                ('udhyam_aadhar_certificate_number', models.CharField(max_length=64, verbose_name='Udhyam Aadhar Certificate Number')),
                ('dpiit_certificate_number', models.CharField(max_length=64, verbose_name='DPIIT Certificate Number')),
                ('llpin', models.CharField(max_length=64, verbose_name='LLPIN')),
                ('website', models.GenericIPAddressField(verbose_name='Website')),
                ('no_of_directors', models.CharField(max_length=64, verbose_name='No. of Directors')),
                ('project_name', models.CharField(max_length=64, verbose_name='Project Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('trustee_name', models.CharField(max_length=64, verbose_name='Trustee Name')),
                ('designation', models.CharField(max_length=64, verbose_name='Designation')),
                ('director_no', models.CharField(max_length=64, verbose_name='Director No')),
                ('pan_no', models.CharField(max_length=64, verbose_name='PAN No')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_directors', to='ngo.organization')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('account_name', models.CharField(max_length=64, verbose_name='Account Name')),
                ('account_number', models.CharField(max_length=64, verbose_name='Account Number')),
                ('account_type', models.CharField(max_length=64, verbose_name='Account Type')),
                ('ifsc_code', models.CharField(max_length=64, verbose_name='IFSC Code')),
                ('bank_name', models.CharField(max_length=64, verbose_name='Bank Name')),
                ('bank_branch', models.CharField(max_length=64, verbose_name='Bank Branch')),
                ('upi_number', models.CharField(max_length=64, verbose_name='UPI Number')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'A user with that phone already exists.'}, max_length=128, region=None, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_bank', to='ngo.organization')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
    ]
