# Generated by Django 4.2.1 on 2023-07-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_alter_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='no_of_directors',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='No. of Directors'),
        ),
    ]
