# Generated by Django 4.2.1 on 2023-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_alter_organization_no_of_directors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
