# Generated by Django 4.2.1 on 2023-07-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_alter_organization_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(verbose_name='Website'),
        ),
    ]
