# Generated by Django 4.2.1 on 2023-07-17 13:58

import activityngo.utils.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0007_alter_organization_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('tagline', models.CharField(max_length=64, verbose_name='Tagline')),
                ('llp_Certificate', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_llp_Certificate_path, verbose_name='LLP Certificate')),
                ('gstin_document', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_gstin_document_path, verbose_name='GSTIN Document')),
                ('udhyam_aadhar_document', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_udhyam_aadhar_document_path, verbose_name='Udhyam Aadhar Document')),
                ('dpiit_document', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_dpiit_document_path, verbose_name='DPIIT Document')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_pan_card_path, verbose_name='PAN Card')),
                ('tan_card', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_tan_card_path, verbose_name='TAN Card')),
                ('logo', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_logo_path, verbose_name='Logo')),
                ('trustee_1_Aadhar_card', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_trustee_1_Aadhar_card_path, verbose_name='Trustee - 1 Aadhar Card')),
                ('trustee_2_aadhar_card', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_trustee_2_aadhar_card_path, verbose_name='Trustee - 2 Aadhar Card')),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_cancelled_cheque_path, verbose_name='Cancelled Cheque')),
                ('seal_and_sign_of_director_1', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_seal_and_sign_of_director_1_path, verbose_name='Seal and Sign of Director 1')),
                ('seal_and_sign_of_director_2', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_seal_and_sign_of_director_2_path, verbose_name='Seal and Sign of Director 2')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_attachments', to='ngo.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
