# Generated by Django 4.2.1 on 2023-07-18 08:38

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0008_organizationattachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgoCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('meta_key', models.CharField(choices=[('terms_condition', 'Terms and Conditions'), ('about_us', 'About Us'), ('privacy_policy', 'Privacy Policy')], max_length=32)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='slug')),
                ('meta_value', tinymce.models.HTMLField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_cms', to='ngo.organization')),
            ],
            options={
                'verbose_name': 'Ngo CMS',
                'verbose_name_plural': 'Ngo CMS',
                'unique_together': {('organization', 'meta_key')},
            },
        ),
    ]
