# Generated by Django 4.2.1 on 2023-07-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0009_ngocms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('ngo_name', models.CharField(max_length=35, unique=True)),
                ('franchise_code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
