# Generated by Django 4.2.1 on 2023-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0011_alter_ngo_franchise_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='franchise_code_count',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='franchise_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
