# Generated by Django 4.2.1 on 2023-07-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0013_alter_ngo_ngo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='ngo_name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
