# Generated by Django 4.2.1 on 2023-07-24 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ngo', '0014_alter_ngo_ngo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('entity_name', models.CharField(max_length=50, verbose_name='Entity Name')),
                ('entity_name_in_report', models.CharField(max_length=40, verbose_name='Entity Name in Report')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('geo_tag', models.CharField(max_length=40, verbose_name='GEO Tag')),
                ('gstin', models.CharField(max_length=64, verbose_name='GSTIN')),
                ('pan_no', models.CharField(max_length=64, verbose_name='PAN No')),
                ('tan_no', models.CharField(max_length=64, verbose_name='TAN No')),
                ('ngo_commission_percentage', models.FloatField(max_length=20, verbose_name='NGO Commission in Percentage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_franchise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
