# Generated by Django 4.2.1 on 2023-07-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0016_franchise_ngo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='franchise_code_count',
        ),
    ]
