# Generated by Django 4.2.1 on 2023-07-24 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ngo', '0017_remove_ngo_franchise_code_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='ngo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_franchise', to='ngo.ngo'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_franchise', to=settings.AUTH_USER_MODEL),
        ),
    ]
