# Generated by Django 4.2.1 on 2023-07-25 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0018_alter_franchise_ngo_alter_franchise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_organization', to='ngo.franchise'),
        ),
    ]
