# Generated by Django 4.2.1 on 2023-07-25 08:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0019_organization_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='Email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'A user with that phone already exists.'}, max_length=128, null=True, region=None, unique=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_location_state',
            field=models.CharField(max_length=64, null=True, verbose_name='Organization Location State'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Organization Name'),
        ),
    ]
