# Generated by Django 4.2.1 on 2023-07-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0020_organization_email_organization_contact_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='Email',
            new_name='email',
        ),
    ]
