# Generated by Django 4.2.1 on 2023-07-25 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ngo', '0021_rename_email_organization_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='franchise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_organization', to='ngo.franchise'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
