# Generated by Django 4.2.1 on 2023-07-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0022_alter_organization_franchise_alter_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directors',
            name='director_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Director No'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='pan_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='PAN No'),
        ),
    ]
