# Generated by Django 4.2.1 on 2023-08-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0023_alter_directors_director_no_alter_directors_pan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngocms',
            name='meta_key',
            field=models.CharField(choices=[('terms_condition', 'Terms and Conditions'), ('our_work', 'OUR WORK'), ('activity_point_projects', 'Activity Point Projects'), ('contact_us', 'Contact Us')], max_length=32),
        ),
    ]
