# Generated by Django 4.2.1 on 2023-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_university_disable_date'),
        ('entities', '0005_batches_disable_date'),
        ('ngo', '0024_alter_ngocms_meta_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='state',
            field=models.ManyToManyField(to='entities.state'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='university',
            field=models.ManyToManyField(to='university.university'),
        ),
    ]
