# Generated by Django 4.2.1 on 2023-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_university_disable_date'),
        ('ngo', '0025_ngo_state_ngo_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='university',
            field=models.ManyToManyField(null=True, to='university.university'),
        ),
    ]
