# Generated by Django 4.2.1 on 2023-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_batches_disable_date'),
        ('ngo', '0026_alter_ngo_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='state',
            field=models.ManyToManyField(null=True, to='entities.state'),
        ),
    ]
