# Generated by Django 4.2.1 on 2023-08-07 05:24

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0029_alter_ngo_state_alter_ngo_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationattachments',
            name='franchise_certificate',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_logo_path, verbose_name='Franchise Certificate'),
        ),
        migrations.AddField(
            model_name='organizationattachments',
            name='ngo_office_photo',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_logo_path, verbose_name='NGO Office Photo'),
        ),
        migrations.AddField(
            model_name='organizationattachments',
            name='seal_and_sign_of_trustee_3',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_logo_path, verbose_name='Seal and Sign of Trustee 3'),
        ),
    ]
