# Generated by Django 4.2.1 on 2023-08-07 05:28

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0030_organizationattachments_franchise_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationattachments',
            name='franchise_certificate',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_franchise_certificate_path, verbose_name='Franchise Certificate'),
        ),
        migrations.AlterField(
            model_name='organizationattachments',
            name='ngo_office_photo',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_ngo_office_photo_path, verbose_name='NGO Office Photo'),
        ),
        migrations.AlterField(
            model_name='organizationattachments',
            name='seal_and_sign_of_trustee_3',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_seal_and_sign_of_trustee_3_path, verbose_name='Seal and Sign of Trustee 3'),
        ),
    ]
