# Generated by Django 4.2.1 on 2023-08-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0032_organizationattachments_trust_deed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='disable_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
