# Generated by Django 4.2.1 on 2023-08-17 06:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0033_ngo_disable_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('meta_value', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ngocms',
            name='meta_key',
            field=models.CharField(choices=[('about_us', 'about_us'), ('our_work', 'OUR WORK'), ('activity_point_projects', 'Activity Point Projects'), ('contact_us', 'Contact Us')], max_length=32),
        ),
    ]
