# Generated by Django 4.2.1 on 2023-09-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0034_ngocollaboration_alter_ngocms_meta_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='franchise_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Franchise code'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='ngo_name',
            field=models.CharField(max_length=35, unique=True, verbose_name='Ngo name'),
        ),
    ]
