# Generated by Django 4.2.5 on 2023-10-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0035_alter_ngo_franchise_code_alter_ngo_ngo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngocollaboration',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True, verbose_name='slug'),
        ),
    ]
