# Generated by Django 4.2.5 on 2023-10-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0037_ngocollaboration_meta_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cinno',
            field=models.CharField(max_length=64, null=True, verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ngo_darpan_no',
            field=models.CharField(max_length=64, null=True, verbose_name='Organization Type'),
        ),
    ]
