# Generated by Django 4.2.5 on 2023-11-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0038_organization_cinno_organization_ngo_darpan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='geo_tag',
            field=models.CharField(max_length=64, verbose_name='GEO Tag'),
        ),
    ]
