# Generated by Django 4.2.5 on 2024-01-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0039_alter_franchise_geo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='tan_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='TAN No'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cinno',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Organization Type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ngo_darpan_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Organization Type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tan_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='TAN No'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
