# Generated by Django 4.2.5 on 2024-02-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0040_alter_franchise_tan_no_alter_organization_cinno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Username'),
        ),
    ]
