# Generated by Django 4.2.1 on 2023-07-13 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('alternate_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A user with that phone already exists.'}, max_length=128, null=True, region=None, unique=True, verbose_name='Alternate Mobile Number')),
                ('alternate_email', models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=254, null=True, unique=True, verbose_name='Alternate Email Address')),
                ('employee_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Employee Number')),
                ('designation', models.CharField(blank=True, max_length=16, null=True, verbose_name='Designation')),
                ('pan_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='PAN No')),
                ('aadhar_no', models.CharField(blank=True, max_length=16, null=True, verbose_name='Aadhar No')),
                ('blood_group', models.CharField(blank=True, max_length=16, null=True, verbose_name='Blood Group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subAdmin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub Admin',
                'verbose_name_plural': 'Sub Admins',
            },
        ),
    ]
