# Generated by Django 4.2.1 on 2023-08-02 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_admin', '0002_subadmin_disable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subAdmin', to=settings.AUTH_USER_MODEL),
        ),
    ]
