# Generated by Django 4.2.1 on 2023-09-08 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_admin', '0004_custompermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read_access', models.BooleanField(default=False, verbose_name='Read Access')),
                ('is_update_access', models.BooleanField(default=False, verbose_name='Update Access')),
                ('custom_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_admin.custompermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
