# Generated by Django 4.2.1 on 2023-09-08 06:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_admin', '0005_useraccesspermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccesspermission',
            options={'verbose_name': 'User Access Permission', 'verbose_name_plural': 'User Access Permission'},
        ),
        migrations.AlterUniqueTogether(
            name='useraccesspermission',
            unique_together={('user', 'custom_permission')},
        ),
    ]
