# Generated by Django 4.2.1 on 2023-09-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0007_subadminaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadminaccesslog',
            name='module_name',
            field=models.CharField(default='test', max_length=255, verbose_name='Module name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subadminaccesslog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Action'),
        ),
    ]
