# Generated by Django 4.2.1 on 2023-09-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0008_subadminaccesslog_module_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subadminaccesslog',
            old_name='module_name',
            new_name='model_name',
        ),
    ]
