# Generated by Django 4.2.1 on 2023-09-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0009_rename_module_name_subadminaccesslog_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmin',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Aadhar No'),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='blood_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Designation'),
        ),
    ]
