# Generated by Django 4.2.1 on 2023-09-15 05:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_admin', '0010_alter_subadmin_aadhar_no_alter_subadmin_blood_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubAdminAccessLog',
            new_name='UserAdminAccessLog',
        ),
    ]
