# Generated by Django 4.2.1 on 2023-09-15 08:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0011_rename_subadminaccesslog_useradminaccesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmin',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Alternate Email Address'),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='alternate_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Alternate Mobile Number'),
        ),
    ]
