# Generated by Django 4.2.5 on 2023-09-22 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_admin', '0013_delete_useraccesspermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_read_access', models.BooleanField(default=False, verbose_name='Read Access')),
                ('is_update_access', models.BooleanField(default=False, verbose_name='Update Access')),
                ('custom_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_admin.custompermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Access Permission',
                'verbose_name_plural': 'User Access Permission',
                'unique_together': {('user', 'custom_permission')},
            },
        ),
    ]
