# Generated by Django 4.2.1 on 2023-08-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0003_alter_subadmin_user'),
        ('student', '0004_aicterules_implementation_necessity_ourteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('complaint_number', models.CharField(max_length=8, verbose_name='Complaint number')),
                ('priority', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16, null=True, verbose_name='Priority')),
                ('status', models.CharField(choices=[('open', 'Open'), ('processing', 'Processing'), ('closed', 'Closed')], default='open', max_length=16, verbose_name='Status')),
                ('allotted_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='allotted_to', to='sub_admin.subadmin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_complaints', to='student.studentdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
