# Generated by Django 4.2.1 on 2023-09-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_complaints_options_complaints_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='student_membership_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Student Membership id'),
        ),
    ]
