# Generated by Django 4.2.1 on 2023-09-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentdetails_student_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='deactivation_date',
            field=models.DateTimeField(null=True, verbose_name='deactivation date'),
        ),
    ]
