# Generated by Django 4.2.1 on 2023-09-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_delete_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUS',
        ),
    ]
