# Generated by Django 4.2.5 on 2023-09-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_delete_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='student_ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Student IP Address'),
        ),
    ]
