# Generated by Django 4.2.5 on 2023-09-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentdetails_student_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='resolution_provided',
            field=models.CharField(max_length=512, null=True, verbose_name='Resolution Provided'),
        ),
    ]
