# Generated by Django 4.2.5 on 2023-09-29 06:51

import activityngo.student.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_complaints_resolution_provided'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('OTP', models.PositiveIntegerField(blank=True, null=True, verbose_name='OTP')),
                ('expiration_time', models.DateTimeField(default=activityngo.student.utils.set_otp_expiration_time)),
                ('is_verified', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
