# Generated by Django 4.2.5 on 2023-10-09 10:26

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_rename_otp_studentotp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_complaint_path, verbose_name='upload_file'),
        ),
    ]
