# Generated by Django 4.2.5 on 2023-10-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_complaints_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaint_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Complaint number'),
        ),
    ]
