# Generated by Django 4.2.5 on 2023-10-09 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0017_alter_complaints_complaint_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='student',
        ),
        migrations.AddField(
            model_name='complaints',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
