# Generated by Django 4.2.5 on 2023-12-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_remove_complaints_student_complaints_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='google_full_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Google full name'),
        ),
    ]
