# Generated by Django 4.2.5 on 2024-02-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0026_alter_college_name'),
        ('student', '0021_alter_complaints_allotted_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_batch', to='college.branchbatches', verbose_name='Student Batch'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_branch', to='college.degreebranch', verbose_name='Student Branch'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_degree', to='college.collegedegree', verbose_name='Student Degree'),
        ),
    ]
