# Generated by Django 4.2.5 on 2024-03-11 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0014_useraccesspermission'),
        ('student', '0022_alter_studentdetails_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='allotted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotted_to', to='sub_admin.subadmin'),
        ),
    ]
