# Generated by Django 4.2.1 on 2023-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('discount_name', models.CharField(max_length=60, verbose_name='discount_name')),
                ('type_discount', models.CharField(choices=[('individual_discount', 'Individual Discount'), ('general_discount', 'General Discount')], max_length=30)),
                ('discount_price_project_type_20', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount price project type 20')),
                ('discount_price_project_type_10', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount price project type 10')),
                ('discount_price_project_type_05', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount price project type 05')),
                ('conjunction_discount', models.BooleanField(verbose_name='Conjunction discount')),
                ('usage_limit', models.PositiveIntegerField(verbose_name='Usage limit')),
                ('usage_limit_per_membership_id', models.PositiveIntegerField(verbose_name='Usage limit per membership id')),
                ('usage_limit_per_project_subscription', models.PositiveIntegerField(verbose_name='Usage Limit per Project Subscription')),
                ('active_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
