# Generated by Django 4.2.1 on 2023-08-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_alter_discountusage_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='current_discount_usage_count',
            field=models.IntegerField(default=0, verbose_name='current_discount_usage_count'),
        ),
    ]
