# Generated by Django 4.2.1 on 2023-08-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_discount_current_discount_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_limit_reached',
            field=models.BooleanField(default=False, verbose_name='discount limit reached'),
        ),
    ]
