# Generated by Django 4.2.1 on 2023-08-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_discount_discount_limit_reached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountusage',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to='discount.discount'),
        ),
    ]
