# Generated by Django 4.2.1 on 2023-09-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_alter_discount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type_discount',
            field=models.CharField(choices=[('individual_discount', 'Individual Discount'), ('general_discount', 'General Discount'), ('batch_discount', 'Batch Discount')], max_length=30),
        ),
    ]
