# Generated by Django 4.2.1 on 2023-09-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_universitycollaboration_universitycms'),
        ('entities', '0005_batches_disable_date'),
        ('college', '0018_alter_collegebatches_college_degree'),
        ('discount', '0009_alter_discount_type_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_batch_discount', to='entities.batches', verbose_name='Student Batch'),
        ),
        migrations.AddField(
            model_name='discount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_branch_discount', to='entities.branch', verbose_name='Student Branch'),
        ),
        migrations.AddField(
            model_name='discount',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_college_discount', to='college.college', verbose_name='Student College'),
        ),
        migrations.AddField(
            model_name='discount',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_degree_discount', to='entities.degree', verbose_name='Student Degree'),
        ),
        migrations.AddField(
            model_name='discount',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_university_discount', to='university.university', verbose_name='Student University'),
        ),
    ]
