# Generated by Django 4.2.1 on 2023-09-08 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0010_discount_batch_discount_branch_discount_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='user',
        ),
        migrations.AddField(
            model_name='discount',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
