# Generated by Django 4.2.5 on 2023-10-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0011_remove_discount_user_discount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
    ]
