# Generated by Django 4.2.5 on 2024-02-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0026_alter_college_name'),
        ('discount', '0012_discount_code_discount_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_batch_discount', to='college.branchbatches', verbose_name='Student Batch'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_branch_discount', to='college.degreebranch', verbose_name='Student Branch'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_degree_discount', to='college.collegedegree', verbose_name='Student Degree'),
        ),
    ]
