# Generated by Django 4.2.5 on 2024-02-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_alter_batches_year'),
        ('discount', '0013_alter_discount_batch_alter_discount_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_college_states', to='entities.state', verbose_name='Student College State'),
        ),
    ]
