# Generated by Django 4.2.1 on 2023-07-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_branch_name_alter_degree_name_and_more'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='project_category',
        ),
        migrations.RemoveField(
            model_name='university',
            name='state',
        ),
        migrations.AddField(
            model_name='university',
            name='project_category',
            field=models.ManyToManyField(to='entities.projectcategory'),
        ),
        migrations.AddField(
            model_name='university',
            name='state',
            field=models.ManyToManyField(to='entities.state'),
        ),
    ]
