# Generated by Django 4.2.1 on 2023-08-21 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_project_is_basic_details_project_is_project_details_and_more'),
        ('cart', '0004_cart_delete_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'project')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
