# Generated by Django 4.2.1 on 2023-08-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_discountcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
