# Generated by Django 4.2.1 on 2023-08-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_discountcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.discountcode'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_expire',
            field=models.BooleanField(default=False, verbose_name='is_expire'),
        ),
    ]
