# Generated by Django 4.2.1 on 2023-08-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projectprice_options_and_more'),
        ('cart', '0011_order_discount_code_order_is_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='project_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product_price_details', to='project.projectprice'),
        ),
    ]
