# Generated by Django 4.2.1 on 2023-08-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_orderdetail_project_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='project_price',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
