# Generated by Django 4.2.1 on 2023-08-23 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_types', '0026_alter_dropdownquestion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0007_orderdetail_number_of_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Submitted', 'Submitted')], max_length=10, verbose_name='Status')),
                ('order_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_question_order_details', to='order.orderdetail')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_question_answers', to='question_types.videoquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_question_answers_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Question Answers',
                'verbose_name_plural': 'Video Questions Answers',
                'unique_together': {('question', 'user')},
            },
        ),
    ]
