# Generated by Django 4.2.1 on 2023-08-25 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0028_taskinstructions_task_completed_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0010_alter_order_order_number_alter_order_user'),
        ('student_project', '0003_alter_essayquestionanswers_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortQuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Submitted', 'Submitted')], max_length=10, verbose_name='Status')),
                ('answer', models.CharField(blank=True, max_length=512, null=True, verbose_name='Answer')),
                ('order_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_question_order_details', to='order.orderdetail')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_question_answers', to='question_types.shortanswerquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_question_answers_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Short Question Answers',
                'verbose_name_plural': 'Short Questions Answers',
                'unique_together': {('question', 'user', 'order_details')},
            },
        ),
    ]
