# Generated by Django 4.2.1 on 2023-08-25 09:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_types', '0029_taskinstructions_number_of_surveys'),
        ('order', '0010_alter_order_order_number_alter_order_user'),
        ('student_project', '0005_exitquestionanswers_mcqquestionanswers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dropdownquestionanswers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='essayquestionanswers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exitquestionanswers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestionanswers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='numericquestionanswers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='percentagequestionanswers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shortquestionanswers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='uploadphotoquestionanswers',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dropdownquestionanswers',
            name='survey_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Survey Form Number'),
        ),
        migrations.AddField(
            model_name='essayquestionanswers',
            name='survey_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Survey Form Number'),
        ),
        migrations.AddField(
            model_name='exitquestionanswers',
            name='survey_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Survey Form Number'),
        ),
        migrations.AddField(
            model_name='mcqquestionanswers',
            name='survey_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Survey Form Number'),
        ),
        migrations.AddField(
            model_name='numericquestionanswers',
            name='survey_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Survey Form Number'),
        ),
        migrations.AddField(
            model_name='percentagequestionanswers',
            name='survey_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Survey Form Number'),
        ),
        migrations.AddField(
            model_name='shortquestionanswers',
            name='survey_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Survey Form Number'),
        ),
        migrations.AddField(
            model_name='uploadphotoquestionanswers',
            name='survey_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Survey Form Number'),
        ),
        migrations.AlterUniqueTogether(
            name='dropdownquestionanswers',
            unique_together={('question', 'user', 'order_details', 'survey_number')},
        ),
        migrations.AlterUniqueTogether(
            name='essayquestionanswers',
            unique_together={('question', 'user', 'order_details', 'survey_number')},
        ),
        migrations.AlterUniqueTogether(
            name='exitquestionanswers',
            unique_together={('question', 'user', 'order_details', 'survey_number')},
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestionanswers',
            unique_together={('question', 'user', 'order_details', 'survey_number')},
        ),
        migrations.AlterUniqueTogether(
            name='numericquestionanswers',
            unique_together={('question', 'user', 'order_details', 'survey_number')},
        ),
        migrations.AlterUniqueTogether(
            name='percentagequestionanswers',
            unique_together={('question', 'user', 'order_details', 'survey_number')},
        ),
        migrations.AlterUniqueTogether(
            name='shortquestionanswers',
            unique_together={('question', 'user', 'order_details', 'survey_number')},
        ),
        migrations.AlterUniqueTogether(
            name='uploadphotoquestionanswers',
            unique_together={('question', 'user', 'order_details', 'survey_number')},
        ),
        migrations.CreateModel(
            name='SurveysDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('survey_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Survey Form Number')),
                ('main_task_number', models.CharField(choices=[('task_1', 'Task – 1'), ('task_2', 'Task – 2'), ('task_3', 'Task – 3'), ('task_4', 'Task – 4'), ('task_5', 'Task – 5'), ('task_6', 'Task – 6'), ('task_7', 'Task – 7'), ('task_8', 'Task – 8'), ('task_9', 'Task – 9'), ('task_10', 'Task – 10')], max_length=10, verbose_name='Main task number')),
                ('order_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task3_surveys_details_order_details', to='order.orderdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task3_surveys_details_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surveys Details',
                'verbose_name_plural': 'Surveys Details',
                'unique_together': {('user', 'order_details', 'survey_number', 'main_task_number')},
            },
        ),
    ]
