# Generated by Django 4.2.1 on 2023-08-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_project', '0006_alter_dropdownquestionanswers_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownquestionanswers',
            name='answer',
        ),
        migrations.CreateModel(
            name='DropDownSelectedOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(blank=True, max_length=512, null=True, verbose_name='Answer')),
                ('question_answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_selected_options', to='student_project.dropdownquestionanswers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
