# Generated by Django 4.2.5 on 2023-10-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_cgst_order_igst_order_sgst'),
        ('student_project', '0007_remove_dropdownquestionanswers_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('student_task_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('answer_rejected_in_evaluation', 'Answer Rejected in Evaluation'), ('submitted_for_evaluation', 'Submitted for Evaluation'), ('all_answers_are_accepted', 'All answers are accepted')], max_length=30, verbose_name='Task Status')),
                ('order_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_task_status_order_details', to='order.orderdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
