# Generated by Django 4.2.5 on 2023-10-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_project', '0008_studenttaskstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttaskstatus',
            name='student_task_status',
        ),
        migrations.AddField(
            model_name='studenttaskstatus',
            name='task1',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('answer_rejected_in_evaluation', 'Answer Rejected in Evaluation'), ('submitted_for_evaluation', 'Submitted for Evaluation'), ('all_answers_are_accepted', 'All answers are accepted')], max_length=30, null=True, verbose_name='Task 1'),
        ),
        migrations.AddField(
            model_name='studenttaskstatus',
            name='task10',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('answer_rejected_in_evaluation', 'Answer Rejected in Evaluation'), ('submitted_for_evaluation', 'Submitted for Evaluation'), ('all_answers_are_accepted', 'All answers are accepted')], max_length=30, null=True, verbose_name='Task 10'),
        ),
        migrations.AddField(
            model_name='studenttaskstatus',
            name='task2',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('answer_rejected_in_evaluation', 'Answer Rejected in Evaluation'), ('submitted_for_evaluation', 'Submitted for Evaluation'), ('all_answers_are_accepted', 'All answers are accepted')], max_length=30, null=True, verbose_name='Task 2'),
        ),
        migrations.AddField(
            model_name='studenttaskstatus',
            name='task3',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('answer_rejected_in_evaluation', 'Answer Rejected in Evaluation'), ('submitted_for_evaluation', 'Submitted for Evaluation'), ('all_answers_are_accepted', 'All answers are accepted')], max_length=30, null=True, verbose_name='Task 3'),
        ),
        migrations.AddField(
            model_name='studenttaskstatus',
            name='task4',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('answer_rejected_in_evaluation', 'Answer Rejected in Evaluation'), ('submitted_for_evaluation', 'Submitted for Evaluation'), ('all_answers_are_accepted', 'All answers are accepted')], max_length=30, null=True, verbose_name='Task 4'),
        ),
        migrations.AddField(
            model_name='studenttaskstatus',
            name='task5',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('answer_rejected_in_evaluation', 'Answer Rejected in Evaluation'), ('submitted_for_evaluation', 'Submitted for Evaluation'), ('all_answers_are_accepted', 'All answers are accepted')], max_length=30, null=True, verbose_name='Task 5'),
        ),
        migrations.AddField(
            model_name='studenttaskstatus',
            name='task6',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('answer_rejected_in_evaluation', 'Answer Rejected in Evaluation'), ('submitted_for_evaluation', 'Submitted for Evaluation'), ('all_answers_are_accepted', 'All answers are accepted')], max_length=30, null=True, verbose_name='Task 6'),
        ),
        migrations.AddField(
            model_name='studenttaskstatus',
            name='task7',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('answer_rejected_in_evaluation', 'Answer Rejected in Evaluation'), ('submitted_for_evaluation', 'Submitted for Evaluation'), ('all_answers_are_accepted', 'All answers are accepted')], max_length=30, null=True, verbose_name='Task 7'),
        ),
        migrations.AddField(
            model_name='studenttaskstatus',
            name='task8',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('answer_rejected_in_evaluation', 'Answer Rejected in Evaluation'), ('submitted_for_evaluation', 'Submitted for Evaluation'), ('all_answers_are_accepted', 'All answers are accepted')], max_length=30, null=True, verbose_name='Task 8'),
        ),
        migrations.AddField(
            model_name='studenttaskstatus',
            name='task9',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('answer_rejected_in_evaluation', 'Answer Rejected in Evaluation'), ('submitted_for_evaluation', 'Submitted for Evaluation'), ('all_answers_are_accepted', 'All answers are accepted')], max_length=30, null=True, verbose_name='Task 9'),
        ),
    ]
