# Generated by Django 4.2.5 on 2023-10-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_project', '0010_alter_studenttaskstatus_task1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttaskstatus',
            name='task2_submissions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
