# Generated by Django 4.2.5 on 2023-10-16 14:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_gst_charges'),
        ('question_types', '0031_videoquestion_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_project', '0013_alter_dropdownquestionanswers_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoquestionanswers',
            unique_together={('question', 'user', 'order_details')},
        ),
    ]
