# Generated by Django 4.2.5 on 2023-10-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_project', '0016_mcqquestionanswers_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQSelectedOptions',
        ),
    ]
