# Generated by Django 4.2.5 on 2023-10-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_gst_charges'),
        ('student_project', '0017_delete_mcqselectedoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttaskstatus',
            name='order_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_task_status_order_details', to='order.orderdetail'),
        ),
    ]
