# Generated by Django 4.2.5 on 2023-10-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_project', '0018_alter_studenttaskstatus_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttaskstatus',
            name='task3_submissions',
            field=models.PositiveIntegerField(default=0, verbose_name='task 3 submissions'),
        ),
    ]
