# Generated by Django 4.2.5 on 2023-10-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0031_videoquestion_thumbnail'),
        ('student_project', '0019_alter_studenttaskstatus_task3_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownquestionanswers',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_question_answers', to='question_types.dropdownquestionoption'),
        ),
        migrations.DeleteModel(
            name='DropDownSelectedOptions',
        ),
    ]
