# Generated by Django 4.2.5 on 2024-01-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_project', '0022_dropdownquestionanswers_reject_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericquestionanswers',
            name='answer',
            field=models.FloatField(blank=True, max_length=512, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='percentagequestionanswers',
            name='answer',
            field=models.FloatField(blank=True, max_length=512, null=True, verbose_name='Answer'),
        ),
    ]
