# Generated by Django 4.2.5 on 2024-02-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_project', '0023_alter_numericquestionanswers_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayquestionanswers',
            name='answer',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Answer'),
        ),
    ]
