# Generated by Django 4.2.1 on 2023-07-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(error_messages={'unique': 'Branch name already exists.'}, max_length=64, unique=True, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(error_messages={'unique': 'Degree name already exists.'}, max_length=64, unique=True, verbose_name='Degree Name'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(error_messages={'unique': 'Project category name already exists.'}, max_length=64, unique=True, verbose_name='Project Category Name'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='type',
            field=models.CharField(error_messages={'unique': 'Project type already exists.'}, max_length=64, unique=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(error_messages={'unique': 'State name already exists.'}, max_length=64, unique=True, verbose_name='State Name'),
        ),
    ]
