# Generated by Django 4.2.5 on 2023-12-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_alter_branch_name_alter_projectcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='end_year',
            field=models.IntegerField(null=True, verbose_name='End Year'),
        ),
        migrations.AddField(
            model_name='batches',
            name='start_year',
            field=models.IntegerField(null=True, verbose_name='Start Year'),
        ),
    ]
