# Generated by Django 4.2.5 on 2023-12-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_batches_end_year_batches_start_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationBatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('start_year', models.IntegerField(verbose_name='Start Year')),
                ('end_year', models.IntegerField(verbose_name='End Year')),
                ('disable_date', models.DateTimeField(blank=True, null=True, verbose_name='disable date')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
