# Generated by Django 4.2.5 on 2024-01-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_implementationbatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(error_messages={'unique': 'Activity Category name already exists.'}, max_length=240, unique=True, verbose_name='Project Category Name'),
        ),
    ]
