# Generated by Django 4.2.5 on 2024-01-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_projectcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='year',
            field=models.CharField(max_length=64, null=True, verbose_name='Year'),
        ),
    ]
