# Generated by Django 4.2.5 on 2024-02-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_alter_batches_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implementationbatches',
            options={'verbose_name': 'ImplementationBatches', 'verbose_name_plural': 'ImplementationBatches'},
        ),
        migrations.RemoveField(
            model_name='batches',
            name='year',
        ),
    ]
