# Generated by Django 4.2.5 on 2024-02-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_alter_implementationbatches_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='implementationbatches',
            unique_together={('start_year', 'end_year')},
        ),
    ]
