# Generated by Django 4.2.5 on 2024-03-14 07:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('activity_points_engg', 'Activity Points engg'), ('lgs_research_foundation', 'Lgs Research Foundation')], max_length=40, verbose_name='Domain')),
                ('page', models.CharField(choices=[('what', 'What'), ('where', 'Where'), ('how', 'How'), ('list', 'List'), ('who', 'Who')], max_length=40, verbose_name='Page')),
                ('meta_value', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Website Content',
                'verbose_name_plural': 'Website Contents',
                'unique_together': {('domain', 'page')},
            },
        ),
    ]
