# Generated by Django 4.2.5 on 2024-03-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitecontent',
            old_name='page',
            new_name='page_name',
        ),
        migrations.AlterUniqueTogether(
            name='websitecontent',
            unique_together={('domain', 'page_name')},
        ),
    ]
