# Generated by Django 4.2.5 on 2024-03-28 05:44

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0002_rename_page_websitecontent_page_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cover_photo', models.ImageField(upload_to=activityngo.utils.utils.get_website_cover_photo_path, verbose_name='Cover photo')),
                ('domain', models.CharField(choices=[('activity_points_engg', 'Activity Points engg'), ('lgs_research_foundation', 'Lgs Research Foundation')], max_length=40, verbose_name='Domain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
