# Generated by Django 4.2.1 on 2023-07-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512, verbose_name='Video Title')),
                ('video_url', models.URLField(max_length=512, verbose_name='Video URL')),
                ('title_max_limit', models.CharField(max_length=512, verbose_name='Video Title Maximum Limit')),
                ('video_url_max_limit', models.URLField(max_length=512, verbose_name='Video URL Maximum Limit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
