# Generated by Django 4.2.1 on 2023-07-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('question_character_maximum_limit', models.CharField(max_length=512, verbose_name='Question Character Maximum Limit')),
                ('copy_paste_question_box', models.BooleanField(verbose_name='Copy – Paste option in Question box')),
                ('special_characters_in_questions', models.BooleanField(verbose_name='Special Characters in Questions')),
                ('action_needed', models.CharField(max_length=512, verbose_name='Action Needed')),
                ('characters_allowed_in_answer_box', models.CharField(max_length=512, verbose_name='Characters allowed in Answer Box')),
                ('special_characters_in_answer_box', models.BooleanField(verbose_name='Special Characters in Answer Box')),
                ('grammar_check_in_answer_box', models.BooleanField(verbose_name='Grammar Check in Answer Box')),
                ('answer_character_minimum_limit', models.BooleanField(verbose_name='Answer Character Minimum Limit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='videoquestion',
            name='title_max_limit',
            field=models.IntegerField(verbose_name='Video Title Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='videoquestion',
            name='video_url_max_limit',
            field=models.IntegerField(verbose_name='Video URL Maximum Limit'),
        ),
    ]
