# Generated by Django 4.2.1 on 2023-07-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0003_shortanswerquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquestion',
            name='answer',
            field=models.CharField(max_length=512, null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='essayquestion',
            name='question',
            field=models.CharField(max_length=512, null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='shortanswerquestion',
            name='answer',
            field=models.CharField(max_length=512, null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='shortanswerquestion',
            name='question',
            field=models.CharField(max_length=512, null=True, verbose_name='Question'),
        ),
    ]
