# Generated by Django 4.2.1 on 2023-07-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0004_essayquestion_answer_essayquestion_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=512, verbose_name='Question')),
                ('answer', models.CharField(max_length=512, verbose_name='Answer')),
                ('question_character_maximum_limit', models.CharField(max_length=512, verbose_name='Question Character Maximum Limit')),
                ('copy_paste_question_box', models.BooleanField(verbose_name='Copy – Paste option in Question box')),
                ('special_characters_in_questions', models.BooleanField(verbose_name='Special Characters in Questions')),
                ('action_needed', models.CharField(max_length=512, verbose_name='Action Needed by Student')),
                ('characters_allowed_in_answer_box', models.IntegerField(verbose_name='Characters allowed in Answer Box')),
                ('no_of_digits_allowed', models.IntegerField(verbose_name='No. of Digits allowed')),
                ('copy_paste_answer_box', models.BooleanField(verbose_name='Copy – Paste option in Answer box')),
                ('answer_character_minimum_limit', models.IntegerField(null=True, verbose_name='Answer Character Minimum Limit')),
                ('answer_character_maximum_limit', models.IntegerField(null=True, verbose_name='Answer Character Maximum Limit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='essayquestion',
            name='answer_character_maximum_limit',
            field=models.IntegerField(null=True, verbose_name='Answer Character Maximum Limit'),
        ),
        migrations.AddField(
            model_name='shortanswerquestion',
            name='answer_character_maximum_limit',
            field=models.IntegerField(null=True, verbose_name='Answer Character Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='answer_character_minimum_limit',
            field=models.IntegerField(null=True, verbose_name='Answer Character Minimum Limit'),
        ),
        migrations.AlterField(
            model_name='shortanswerquestion',
            name='answer_character_minimum_limit',
            field=models.IntegerField(null=True, verbose_name='Answer Character Minimum Limit'),
        ),
    ]
