# Generated by Django 4.2.1 on 2023-07-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0005_numericquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=512, verbose_name='Question')),
                ('answer', models.CharField(max_length=512, verbose_name='Answer')),
                ('special_characters_in_questions', models.BooleanField(verbose_name='Special Characters in Questions')),
                ('action_needed', models.CharField(max_length=512, verbose_name='Action Needed by Student')),
                ('characters_allowed_in_answer_box', models.IntegerField(verbose_name='Characters allowed in Answer Box')),
                ('special_characters_in_answer', models.BooleanField(verbose_name='Special Characters in Answer')),
                ('copy_paste_answer_box', models.BooleanField(verbose_name='Copy – Paste option in Answer box')),
                ('answer_character_minimum_limit', models.IntegerField(null=True, verbose_name='Answer Character Minimum Limit')),
                ('answer_character_maximum_limit', models.IntegerField(null=True, verbose_name='Answer Character Maximum Limit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
