# Generated by Django 4.2.1 on 2023-07-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0006_percentagequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=512, verbose_name='Question')),
                ('number_of_options', models.IntegerField(verbose_name='Number of Options')),
                ('question_character_maximum_limit', models.IntegerField(null=True, verbose_name='Question Character Maximum Limit')),
                ('copy_paste_question_box', models.BooleanField(verbose_name='Copy – Paste option in Question box')),
                ('special_characters_in_questions', models.BooleanField(verbose_name='Special Characters in Questions')),
                ('minimum_number_of_options_in_mcq', models.IntegerField(null=True, verbose_name='Minimum Number of Options in MCQ')),
                ('maximum_number_of_options_in_mcq', models.IntegerField(null=True, verbose_name='Maximum Number of Options in MCQ')),
                ('mcq_options_character_maximum_limit', models.IntegerField(null=True, verbose_name='MCQ Options Character Maximum Limit')),
                ('copy_paste_answer_mcq_option_box', models.BooleanField(verbose_name='Copy – Paste option in Answer box')),
                ('special_characters_in_mcq_option_box', models.BooleanField(verbose_name='Special Characters in MCQ Option box')),
                ('action_needed', models.CharField(max_length=512, verbose_name='Action Needed by Student')),
                ('number_of_options_allowed_to_select_among_mcq', models.IntegerField(null=True, verbose_name='Number of Options allowed to select among MCQ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McqOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('option', models.CharField(max_length=512, verbose_name='Option')),
                ('mca_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mca_question_option', to='question_types.mcqquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
