# Generated by Django 4.2.1 on 2023-08-01 05:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0007_mcqquestion_mcqoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPhotoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=512, verbose_name='Question')),
                ('answer', models.CharField(max_length=512, verbose_name='Answer')),
                ('question_character_maximum_limit', models.IntegerField(null=True, verbose_name='Question Character Maximum Limit')),
                ('copy_paste_question_box', models.BooleanField(verbose_name='Copy – Paste option in Question box')),
                ('special_characters_in_questions', models.BooleanField(verbose_name='Special Characters in Questions')),
                ('action_needed', models.CharField(max_length=512, verbose_name='Action Needed by Student')),
                ('allowed_format', multiselectfield.db.fields.MultiSelectField(choices=[('jpeg', 'JPEG'), ('jpg', 'JPG'), ('png', 'PNG')], max_length=255, verbose_name='Allowed Format')),
                ('minimum_file_size_allowed', models.IntegerField(null=True, verbose_name='Minimum File Size allowed')),
                ('maximum_file_size_allowed', models.IntegerField(null=True, verbose_name='Maximum File Size allowed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
