# Generated by Django 4.2.1 on 2023-08-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0009_exittestquestion_remove_mcqoption_mca_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqoption',
            name='right_answer_option_among_multiple_choice',
            field=models.BooleanField(default=False, verbose_name='right_answer_option_among_multiple_choice'),
        ),
    ]
