# Generated by Django 4.2.1 on 2023-08-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0011_dropdownquestion_dropdownquestionoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('task_instructions', models.CharField(max_length=512, verbose_name='Task Instructions')),
                ('instructions_character_maximum_limit', models.IntegerField(null=True, verbose_name='Instructions Character Maximum Limit:')),
                ('copy_paste_option_in_instruction_box', models.BooleanField(verbose_name='Copy – Paste option in Instruction box')),
                ('special_characters_in_instruction_box', models.BooleanField(verbose_name='Special Characters in Instruction box')),
                ('image_in_instruction_box', models.BooleanField(verbose_name='Image in Instruction box')),
                ('url_in_instruction_box', models.BooleanField(default=True, verbose_name='URL in Instruction box')),
                ('action_needed', models.CharField(max_length=512, verbose_name='Action Needed by Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
