# Generated by Django 4.2.1 on 2023-08-01 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectdetails_can_students_visit_field_by_themselves_and_more'),
        ('question_types', '0012_taskinstructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoquestion',
            name='main_task_number',
            field=models.CharField(choices=[('task_1', 'Task – 1'), ('task_2', 'Task – 2'), ('task_3', 'Task – 3'), ('task_4', 'Task – 4'), ('task_5', 'Task – 5'), ('task_6', 'Task – 6'), ('task_7', 'Task – 7'), ('task_8', 'Task – 8'), ('task_9', 'Task – 9'), ('task_10', 'Task – 10')], max_length=10, null=True, verbose_name='Main task number'),
        ),
        migrations.AddField(
            model_name='videoquestion',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mca_question_option', to='project.project'),
        ),
        migrations.AddField(
            model_name='videoquestion',
            name='sub_task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Sub task number'),
        ),
    ]
