# Generated by Django 4.2.1 on 2023-08-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectdetails_can_students_visit_field_by_themselves_and_more'),
        ('question_types', '0013_videoquestion_main_task_number_videoquestion_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoquestion',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_question_projects', to='project.project'),
        ),
    ]
