# Generated by Django 4.2.1 on 2023-08-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectdetails_can_students_visit_field_by_themselves_and_more'),
        ('question_types', '0014_alter_videoquestion_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqoption',
            name='exit_test_question',
        ),
        migrations.AddField(
            model_name='dropdownquestion',
            name='main_task_number',
            field=models.CharField(choices=[('task_1', 'Task – 1'), ('task_2', 'Task – 2'), ('task_3', 'Task – 3'), ('task_4', 'Task – 4'), ('task_5', 'Task – 5'), ('task_6', 'Task – 6'), ('task_7', 'Task – 7'), ('task_8', 'Task – 8'), ('task_9', 'Task – 9'), ('task_10', 'Task – 10')], max_length=10, null=True, verbose_name='Main task number'),
        ),
        migrations.AddField(
            model_name='dropdownquestion',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_question_projects', to='project.project'),
        ),
        migrations.AddField(
            model_name='dropdownquestion',
            name='sub_task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Sub task number'),
        ),
        migrations.AddField(
            model_name='essayquestion',
            name='main_task_number',
            field=models.CharField(choices=[('task_1', 'Task – 1'), ('task_2', 'Task – 2'), ('task_3', 'Task – 3'), ('task_4', 'Task – 4'), ('task_5', 'Task – 5'), ('task_6', 'Task – 6'), ('task_7', 'Task – 7'), ('task_8', 'Task – 8'), ('task_9', 'Task – 9'), ('task_10', 'Task – 10')], max_length=10, null=True, verbose_name='Main task number'),
        ),
        migrations.AddField(
            model_name='essayquestion',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_question_projects', to='project.project'),
        ),
        migrations.AddField(
            model_name='essayquestion',
            name='sub_task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Sub task number'),
        ),
        migrations.AddField(
            model_name='exittestquestion',
            name='main_task_number',
            field=models.CharField(choices=[('task_1', 'Task – 1'), ('task_2', 'Task – 2'), ('task_3', 'Task – 3'), ('task_4', 'Task – 4'), ('task_5', 'Task – 5'), ('task_6', 'Task – 6'), ('task_7', 'Task – 7'), ('task_8', 'Task – 8'), ('task_9', 'Task – 9'), ('task_10', 'Task – 10')], max_length=10, null=True, verbose_name='Main task number'),
        ),
        migrations.AddField(
            model_name='exittestquestion',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_test_question_projects', to='project.project'),
        ),
        migrations.AddField(
            model_name='exittestquestion',
            name='sub_task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Sub task number'),
        ),
        migrations.AddField(
            model_name='mcqoption',
            name='mca_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mca_question_option', to='question_types.mcqquestion'),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='main_task_number',
            field=models.CharField(choices=[('task_1', 'Task – 1'), ('task_2', 'Task – 2'), ('task_3', 'Task – 3'), ('task_4', 'Task – 4'), ('task_5', 'Task – 5'), ('task_6', 'Task – 6'), ('task_7', 'Task – 7'), ('task_8', 'Task – 8'), ('task_9', 'Task – 9'), ('task_10', 'Task – 10')], max_length=10, null=True, verbose_name='Main task number'),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_question_projects', to='project.project'),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='sub_task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Sub task number'),
        ),
        migrations.AddField(
            model_name='numericquestion',
            name='main_task_number',
            field=models.CharField(choices=[('task_1', 'Task – 1'), ('task_2', 'Task – 2'), ('task_3', 'Task – 3'), ('task_4', 'Task – 4'), ('task_5', 'Task – 5'), ('task_6', 'Task – 6'), ('task_7', 'Task – 7'), ('task_8', 'Task – 8'), ('task_9', 'Task – 9'), ('task_10', 'Task – 10')], max_length=10, null=True, verbose_name='Main task number'),
        ),
        migrations.AddField(
            model_name='numericquestion',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numeric_question_projects', to='project.project'),
        ),
        migrations.AddField(
            model_name='numericquestion',
            name='sub_task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Sub task number'),
        ),
        migrations.AddField(
            model_name='percentagequestion',
            name='main_task_number',
            field=models.CharField(choices=[('task_1', 'Task – 1'), ('task_2', 'Task – 2'), ('task_3', 'Task – 3'), ('task_4', 'Task – 4'), ('task_5', 'Task – 5'), ('task_6', 'Task – 6'), ('task_7', 'Task – 7'), ('task_8', 'Task – 8'), ('task_9', 'Task – 9'), ('task_10', 'Task – 10')], max_length=10, null=True, verbose_name='Main task number'),
        ),
        migrations.AddField(
            model_name='percentagequestion',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percentage_question_projects', to='project.project'),
        ),
        migrations.AddField(
            model_name='percentagequestion',
            name='sub_task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Sub task number'),
        ),
        migrations.AddField(
            model_name='shortanswerquestion',
            name='main_task_number',
            field=models.CharField(choices=[('task_1', 'Task – 1'), ('task_2', 'Task – 2'), ('task_3', 'Task – 3'), ('task_4', 'Task – 4'), ('task_5', 'Task – 5'), ('task_6', 'Task – 6'), ('task_7', 'Task – 7'), ('task_8', 'Task – 8'), ('task_9', 'Task – 9'), ('task_10', 'Task – 10')], max_length=10, null=True, verbose_name='Main task number'),
        ),
        migrations.AddField(
            model_name='shortanswerquestion',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_question_projects', to='project.project'),
        ),
        migrations.AddField(
            model_name='shortanswerquestion',
            name='sub_task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Sub task number'),
        ),
        migrations.AddField(
            model_name='taskinstructions',
            name='main_task_number',
            field=models.CharField(choices=[('task_1', 'Task – 1'), ('task_2', 'Task – 2'), ('task_3', 'Task – 3'), ('task_4', 'Task – 4'), ('task_5', 'Task – 5'), ('task_6', 'Task – 6'), ('task_7', 'Task – 7'), ('task_8', 'Task – 8'), ('task_9', 'Task – 9'), ('task_10', 'Task – 10')], max_length=10, null=True, verbose_name='Main task number'),
        ),
        migrations.AddField(
            model_name='taskinstructions',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_instructions_question_projects', to='project.project'),
        ),
        migrations.AddField(
            model_name='taskinstructions',
            name='sub_task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Sub task number'),
        ),
        migrations.AddField(
            model_name='uploadphotoquestion',
            name='main_task_number',
            field=models.CharField(choices=[('task_1', 'Task – 1'), ('task_2', 'Task – 2'), ('task_3', 'Task – 3'), ('task_4', 'Task – 4'), ('task_5', 'Task – 5'), ('task_6', 'Task – 6'), ('task_7', 'Task – 7'), ('task_8', 'Task – 8'), ('task_9', 'Task – 9'), ('task_10', 'Task – 10')], max_length=10, null=True, verbose_name='Main task number'),
        ),
        migrations.AddField(
            model_name='uploadphotoquestion',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_photo_question_projects', to='project.project'),
        ),
        migrations.AddField(
            model_name='uploadphotoquestion',
            name='sub_task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Sub task number'),
        ),
        migrations.CreateModel(
            name='ExitTestQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('option', models.CharField(max_length=512, verbose_name='Option')),
                ('right_answer_option_among_multiple_choice', models.BooleanField(default=False, verbose_name='right_answer_option_among_multiple_choice')),
                ('exit_test_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_test_question_option', to='question_types.exittestquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
