# Generated by Django 4.2.1 on 2023-08-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_projectdetails_project'),
        ('question_types', '0015_remove_mcqoption_exit_test_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoquestion',
            options={'verbose_name': 'Video Question', 'verbose_name_plural': 'Video Questions'},
        ),
        migrations.AlterField(
            model_name='videoquestion',
            name='title_max_limit',
            field=models.PositiveIntegerField(verbose_name='Video Title Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='videoquestion',
            name='video_url_max_limit',
            field=models.PositiveIntegerField(verbose_name='Video URL Maximum Limit'),
        ),
        migrations.AlterUniqueTogether(
            name='videoquestion',
            unique_together={('project', 'main_task_number', 'sub_task_number')},
        ),
    ]
