# Generated by Django 4.2.1 on 2023-08-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_studentfeedback'),
        ('question_types', '0016_alter_videoquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essayquestion',
            options={'verbose_name': 'Essay Question', 'verbose_name_plural': 'Essay Questions'},
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='action_needed',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Action Needed'),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='answer_character_maximum_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Answer Character Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='answer_character_minimum_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Answer Character Minimum Limit'),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='characters_allowed_in_answer_box',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Characters allowed in Answer Box'),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='copy_paste_question_box',
            field=models.BooleanField(default=True, verbose_name='Copy – Paste option in Question box'),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='grammar_check_in_answer_box',
            field=models.BooleanField(blank=True, null=True, verbose_name='Grammar Check in Answer Box'),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='question_character_maximum_limit',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Question Character Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='special_characters_in_answer_box',
            field=models.BooleanField(blank=True, null=True, verbose_name='Special Characters in Answer Box'),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='special_characters_in_questions',
            field=models.BooleanField(default=True, verbose_name='Special Characters in Questions'),
        ),
        migrations.AlterUniqueTogether(
            name='essayquestion',
            unique_together={('project', 'main_task_number', 'sub_task_number')},
        ),
    ]
