# Generated by Django 4.2.1 on 2023-08-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_studentfeedback'),
        ('question_types', '0020_alter_percentagequestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcqquestion',
            options={'verbose_name': 'MCQ Question', 'verbose_name_plural': 'MCQ Questions'},
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='action_needed',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Action Needed by Student'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='copy_paste_answer_mcq_option_box',
            field=models.BooleanField(default=True, verbose_name='Copy – Paste option in Answer box'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='copy_paste_question_box',
            field=models.BooleanField(default=True, verbose_name='Copy – Paste option in Question box'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='maximum_number_of_options_in_mcq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Number of Options in MCQ'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='mcq_options_character_maximum_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='MCQ Options Character Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='minimum_number_of_options_in_mcq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Number of Options in MCQ'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='number_of_options',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Options'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='number_of_options_allowed_to_select_among_mcq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Options allowed to select among MCQ'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='question_character_maximum_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Question Character Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='special_characters_in_mcq_option_box',
            field=models.BooleanField(default=True, verbose_name='Special Characters in MCQ Option box'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='special_characters_in_questions',
            field=models.BooleanField(default=True, verbose_name='Special Characters in Questions'),
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestion',
            unique_together={('project', 'main_task_number', 'sub_task_number')},
        ),
    ]
