# Generated by Django 4.2.1 on 2023-08-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0021_alter_mcqquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcqoption',
            options={'verbose_name': 'MCQ Option', 'verbose_name_plural': 'MCQ Option'},
        ),
    ]
