# Generated by Django 4.2.1 on 2023-08-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0022_alter_mcqoption_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqoption',
            old_name='mca_question',
            new_name='mcq_question',
        ),
    ]
