# Generated by Django 4.2.1 on 2023-08-17 06:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_studentfeedback'),
        ('question_types', '0023_rename_mca_question_mcqoption_mcq_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadphotoquestion',
            options={'verbose_name': 'Upload Photo Question', 'verbose_name_plural': 'Upload Photo Questions'},
        ),
        migrations.AlterField(
            model_name='uploadphotoquestion',
            name='action_needed',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Action Needed by Student'),
        ),
        migrations.AlterField(
            model_name='uploadphotoquestion',
            name='allowed_format',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('jpeg', 'JPEG'), ('jpg', 'JPG'), ('png', 'PNG')], max_length=255, null=True, verbose_name='Allowed Format'),
        ),
        migrations.AlterField(
            model_name='uploadphotoquestion',
            name='copy_paste_question_box',
            field=models.BooleanField(default=True, verbose_name='Copy – Paste option in Question box'),
        ),
        migrations.AlterField(
            model_name='uploadphotoquestion',
            name='maximum_file_size_allowed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum File Size allowed'),
        ),
        migrations.AlterField(
            model_name='uploadphotoquestion',
            name='minimum_file_size_allowed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum File Size allowed'),
        ),
        migrations.AlterField(
            model_name='uploadphotoquestion',
            name='question_character_maximum_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Question Character Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='uploadphotoquestion',
            name='special_characters_in_questions',
            field=models.BooleanField(default=True, verbose_name='Special Characters in Questions'),
        ),
        migrations.AlterUniqueTogether(
            name='uploadphotoquestion',
            unique_together={('project', 'main_task_number', 'sub_task_number')},
        ),
    ]
