# Generated by Django 4.2.1 on 2023-08-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_studentfeedback'),
        ('question_types', '0025_alter_exittestquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropdownquestion',
            options={'verbose_name': 'Dropdown Question', 'verbose_name_plural': 'Dropdown Questions'},
        ),
        migrations.AlterModelOptions(
            name='dropdownquestionoption',
            options={'verbose_name': 'Dropdown Question Option', 'verbose_name_plural': 'Dropdown Questions Option'},
        ),
        migrations.AlterModelOptions(
            name='taskinstructions',
            options={'verbose_name': 'Task Instructions', 'verbose_name_plural': 'Task Instructions'},
        ),
        migrations.AlterField(
            model_name='dropdownquestion',
            name='action_needed',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Action Needed by Student'),
        ),
        migrations.AlterField(
            model_name='dropdownquestion',
            name='copy_paste_answer_mcq_option_box',
            field=models.BooleanField(default=True, verbose_name='Copy – Paste option in Answer box'),
        ),
        migrations.AlterField(
            model_name='dropdownquestion',
            name='copy_paste_question_box',
            field=models.BooleanField(blank=True, null=True, verbose_name='Copy – Paste option in Question box'),
        ),
        migrations.AlterField(
            model_name='dropdownquestion',
            name='number_of_dropdowns_in_mcq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Dropdowns in MCQ'),
        ),
        migrations.AlterField(
            model_name='dropdownquestion',
            name='number_of_options',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Options'),
        ),
        migrations.AlterField(
            model_name='dropdownquestion',
            name='question_character_maximum_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Question Character Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='dropdownquestion',
            name='special_characters_in_mcq_option_box',
            field=models.BooleanField(default=True, verbose_name='Special Characters in MCQ Option box'),
        ),
        migrations.AlterField(
            model_name='dropdownquestion',
            name='special_characters_in_questions',
            field=models.BooleanField(default=True, verbose_name='Special Characters in Questions'),
        ),
        migrations.AlterField(
            model_name='taskinstructions',
            name='action_needed',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Action Needed by Student'),
        ),
        migrations.AlterField(
            model_name='taskinstructions',
            name='copy_paste_option_in_instruction_box',
            field=models.BooleanField(default=True, verbose_name='Copy – Paste option in Instruction box'),
        ),
        migrations.AlterField(
            model_name='taskinstructions',
            name='image_in_instruction_box',
            field=models.BooleanField(default=True, verbose_name='Image in Instruction box'),
        ),
        migrations.AlterField(
            model_name='taskinstructions',
            name='instructions_character_maximum_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Instructions Character Maximum Limit:'),
        ),
        migrations.AlterField(
            model_name='taskinstructions',
            name='special_characters_in_instruction_box',
            field=models.BooleanField(default=True, verbose_name='Special Characters in Instruction box'),
        ),
        migrations.AlterField(
            model_name='taskinstructions',
            name='task_instructions',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Task Instructions'),
        ),
        migrations.AlterUniqueTogether(
            name='dropdownquestion',
            unique_together={('project', 'main_task_number', 'sub_task_number')},
        ),
        migrations.AlterUniqueTogether(
            name='taskinstructions',
            unique_together={('project', 'main_task_number', 'sub_task_number')},
        ),
    ]
