# Generated by Django 4.2.1 on 2023-08-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0026_alter_dropdownquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstructions',
            name='task_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Task Name'),
        ),
    ]
