# Generated by Django 4.2.1 on 2023-08-24 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0027_taskinstructions_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstructions',
            name='task_completed_hours',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total hours for task completed'),
        ),
    ]
