# Generated by Django 4.2.1 on 2023-08-25 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0028_taskinstructions_task_completed_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstructions',
            name='number_of_surveys',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Number of Person with whom surveys are to be conducted'),
        ),
    ]
