# Generated by Django 4.2.1 on 2023-08-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0029_taskinstructions_number_of_surveys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinstructions',
            name='number_of_surveys',
        ),
    ]
