# Generated by Django 4.2.5 on 2023-10-10 06:51

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0030_remove_taskinstructions_number_of_surveys'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoquestion',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_upload_thumbnail_video_question_path, verbose_name='Thumbnail'),
        ),
    ]
