# Generated by Django 4.2.5 on 2023-10-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0031_videoquestion_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentagequestion',
            name='special_characters_in_answer',
        ),
        migrations.AddField(
            model_name='numericquestion',
            name='special_characters_in_answer_box',
            field=models.BooleanField(default=True, verbose_name='Special Characters in Answer Box'),
        ),
        migrations.AddField(
            model_name='percentagequestion',
            name='special_characters_in_answer_box',
            field=models.BooleanField(default=True, verbose_name='Special Characters in Answer Box'),
        ),
    ]
