# Generated by Django 4.2.5 on 2023-10-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0032_remove_percentagequestion_special_characters_in_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquestion',
            name='copy_paste_answer_box',
            field=models.BooleanField(default=True, verbose_name='Copy – Paste option in Answer box'),
        ),
    ]
