# Generated by Django 4.2.5 on 2023-10-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0033_essayquestion_copy_paste_answer_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortanswerquestion',
            name='copy_paste_answer_box',
            field=models.BooleanField(default=True, verbose_name='Copy – Paste option in Answer box'),
        ),
    ]
