# Generated by Django 4.2.5 on 2024-01-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_types', '0036_remove_taskinstructions_action_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoquestion',
            name='title_max_limit',
        ),
        migrations.RemoveField(
            model_name='videoquestion',
            name='video_url_max_limit',
        ),
    ]
