# Generated by Django 4.2.5 on 2023-10-02 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Notification Type')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifications',
            },
        ),
    ]
