# Generated by Django 4.2.1 on 2023-07-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo', '0023_alter_directors_director_no_alter_directors_pan_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBasicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('number_of_points', models.IntegerField(verbose_name='Number of Points')),
                ('number_of_hours', models.IntegerField(verbose_name='Number of Hours')),
                ('category', models.CharField(max_length=50, verbose_name='Project Category')),
                ('type', models.CharField(max_length=50, verbose_name='Project Type')),
                ('title', models.CharField(max_length=50, verbose_name='Project Title')),
                ('expire_duration_in_days_by_students', models.IntegerField(verbose_name='Expire Duration in Days (Project Completion by Students)')),
                ('expire_duration_in_days_by_evaluate', models.IntegerField(verbose_name='Expire Duration in Days (Admin to Evaluate and Generate Report)')),
                ('subscription_price', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Subscription Price')),
                ('minimum_number_of_days', models.IntegerField(verbose_name='Minimum Number of Days')),
                ('gst_inclusive', models.FloatField(max_length=10, verbose_name='GST Inclusive / Exclusive in Project Price')),
                ('franchise_ngo_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_projects', to='ngo.ngo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
