# Generated by Django 4.2.1 on 2023-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_projectbasicdetails_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='can_students_visit_field_by_themselves',
            field=models.BooleanField(default=True, verbose_name='Can students visit field by themselves'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='field_visit_mandation',
            field=models.BooleanField(default=True, verbose_name='Field Visit Mandation'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='issue_of_certificate',
            field=models.CharField(max_length=512, null=True, verbose_name='Issue of Certificate'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='issue_of_report',
            field=models.CharField(max_length=512, null=True, verbose_name='Issue of Report'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='mode_of_receiving_report_and_certificate',
            field=models.CharField(max_length=512, null=True, verbose_name='Mode of Receiving Report & Certificate'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='number_of_tasks',
            field=models.IntegerField(null=True, verbose_name='Number of Tasks'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='places_that_can_be_considered_for_field_visit',
            field=models.CharField(max_length=512, null=True, verbose_name='Places that can be considered for field visit'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='scheduling_field_visit_by_ngo',
            field=models.BooleanField(default=True, verbose_name='Scheduling Field Visit by NGO'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10),
        ),
    ]
