# Generated by Django 4.2.1 on 2023-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectdetails_can_students_visit_field_by_themselves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='number_of_points',
            field=models.CharField(choices=[('points_20', '20 Points'), ('points_10', '10 Points'), ('points_05', '05 Points')], max_length=10),
        ),
    ]
