# Generated by Django 4.2.1 on 2023-08-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_collegecollaboration_collegecms'),
        ('university', '0005_universitycollaboration_universitycms'),
        ('entities', '0005_batches_disable_date'),
        ('project', '0008_project_is_basic_details_project_is_project_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_category_details', to='entities.projectcategory'),
        ),
        migrations.CreateModel(
            name='SpecialPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_special_power', to='entities.batches')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_special_power', to='college.college')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_special_power', to='entities.degree')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_special_power', to='project.project')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_special_power', to='entities.state')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_special_power', to='university.university')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('number_of_hour', models.IntegerField(verbose_name='Number of Hours')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_project_price', to='project.project')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_project_type', to='entities.projecttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
