# Generated by Django 4.2.1 on 2023-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_category_specialpower_projectprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectprice',
            options={'verbose_name': 'Project Price', 'verbose_name_plural': 'Project Price'},
        ),
        migrations.AddField(
            model_name='projectprice',
            name='number_of_points',
            field=models.CharField(choices=[('points_20', '20 Points'), ('points_10', '10 Points'), ('points_05', '05 Points')], default='points_20', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='projectprice',
            unique_together={('number_of_points', 'project')},
        ),
    ]
