# Generated by Django 4.2.1 on 2023-08-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projectprice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprice',
            name='project_type',
        ),
    ]
