# Generated by Django 4.2.1 on 2023-08-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_projectprice_project_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectPrice',
        ),
    ]
