# Generated by Django 4.2.1 on 2023-08-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_delete_projectprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hour_of_05_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Hours of 05 point'),
        ),
        migrations.AddField(
            model_name='project',
            name='hour_of_10_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Hours of 10 point'),
        ),
        migrations.AddField(
            model_name='project',
            name='hour_of_20_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Hours of 20 point'),
        ),
        migrations.AddField(
            model_name='project',
            name='price_of_05_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price of 05 point'),
        ),
        migrations.AddField(
            model_name='project',
            name='price_of_10_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price of 10 point'),
        ),
        migrations.AddField(
            model_name='project',
            name='price_of_20_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price of 20 point'),
        ),
    ]
