# Generated by Django 4.2.1 on 2023-08-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_hour_of_05_point_project_hour_of_10_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='number_of_hours',
        ),
        migrations.RemoveField(
            model_name='project',
            name='number_of_points',
        ),
    ]
