# Generated by Django 4.2.5 on 2023-10-06 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_rename_hour_of_05_point_project_days_of_05_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
