# Generated by Django 4.2.5 on 2023-10-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0035_alter_ngo_franchise_code_alter_ngo_ngo_name'),
        ('entities', '0005_batches_disable_date'),
        ('project', '0016_alter_studentfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_category_details', to='entities.projectcategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='franchise_ngo_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ngo_projects', to='ngo.ngo'),
        ),
    ]
