# Generated by Django 4.2.5 on 2024-02-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_projectdetails_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subscription_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Subscription Price'),
        ),
    ]
