# Generated by Django 4.2.5 on 2024-02-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_alter_project_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='minimum_number_of_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Number of Days'),
        ),
    ]
