# Generated by Django 4.2.5 on 2023-09-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0015_rename_hour_of_05_point_project_days_of_05_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type_point', models.CharField(choices=[('point_20', 'POINT_20'), ('point_10', 'POINT_10'), ('point_05', 'POINT_05')], default='point_20', max_length=40, verbose_name='type point')),
                ('disclaimer', models.TextField(verbose_name='Disclaimer')),
                ('Abstract', models.TextField(verbose_name='Abstract')),
                ('Chapter_01', models.TextField(verbose_name='Chapter 01')),
                ('Chapter_02', models.TextField(verbose_name='Chapter 02')),
                ('Chapter_03', models.TextField(verbose_name='Chapter 03')),
                ('Chapter_04', models.TextField(verbose_name='Chapter 04')),
                ('Chapter_05', models.TextField(verbose_name='Chapter 05')),
                ('Chapter_06', models.TextField(verbose_name='Chapter 06')),
                ('Chapter_07', models.TextField(verbose_name='Chapter 07')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_report_content', to='project.project')),
            ],
            options={
                'verbose_name': 'Report Content',
                'verbose_name_plural': 'Report Content',
                'unique_together': {('project', 'type_point')},
            },
        ),
    ]
