# Generated by Django 4.2.5 on 2023-09-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_report', '0002_rename_abstract_reportcontent_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_01',
            field=models.TextField(blank=True, null=True, verbose_name='Chapter 01'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_02',
            field=models.TextField(blank=True, null=True, verbose_name='Chapter 02'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_03',
            field=models.TextField(blank=True, null=True, verbose_name='Chapter 03'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_04',
            field=models.TextField(blank=True, null=True, verbose_name='Chapter 04'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_05',
            field=models.TextField(blank=True, null=True, verbose_name='Chapter 05'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_06',
            field=models.TextField(blank=True, null=True, verbose_name='Chapter 06'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_07',
            field=models.TextField(blank=True, null=True, verbose_name='Chapter 07'),
        ),
    ]
