# Generated by Django 4.2.5 on 2023-09-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_report', '0003_alter_reportcontent_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='type_point',
            field=models.CharField(choices=[('point_20', 'POINT_20'), ('point_10', 'POINT_10'), ('point_05', 'POINT_05')], max_length=40, verbose_name='type point'),
        ),
    ]
