# Generated by Django 4.2.5 on 2023-09-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_report', '0004_alter_reportcontent_type_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='disclaimer',
            field=models.TextField(blank=True, null=True, verbose_name='Disclaimer'),
        ),
    ]
