# Generated by Django 4.2.5 on 2024-02-05 05:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_report', '0005_alter_reportcontent_disclaimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='abstract',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_01',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_02',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_03',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_04',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_05',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_06',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='chapter_07',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='disclaimer',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
