# Generated by Django 4.2.5 on 2024-02-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_report', '0006_alter_reportcontent_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='type_point',
            field=models.CharField(choices=[('points_20', 'POINT_20'), ('points_10', 'POINT_10'), ('points_05', 'POINT_05')], max_length=40, verbose_name='type point'),
        ),
    ]
