# Generated by Django 4.2.5 on 2024-02-05 07:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_report', '0007_alter_reportcontent_type_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcontent',
            name='appendix',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
