# Generated by Django 4.2.5 on 2024-02-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_report', '0008_reportcontent_appendix'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcontent',
            name='disable_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
