# Generated by Django 4.2.1 on 2023-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('meta_key', models.CharField(choices=[('necessity', 'Necessity'), ('aicte_rules', 'AICTE Rules'), ('university_rules', 'University Rules'), ('implementation_method', 'Implementation Method'), ('terms_and_conditions', 'Terms and Conditions'), ('about_us', 'About US'), ('privacy_policy', 'Privacy Policy'), ('read_instructions', 'Read Instructions')], max_length=32, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, verbose_name='slug')),
                ('meta_value', models.TextField(max_length=2096, verbose_name='Meta Value')),
            ],
            options={
                'verbose_name_plural': 'CMS',
            },
        ),
    ]
