# Generated by Django 4.2.1 on 2023-09-19 05:51

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('buy_projects_text_tutorial', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_text_tutorial_path, verbose_name='text_tutorial')),
                ('buy_projects_screenshot_tutorial', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_screenshot_tutorial_path, verbose_name='text_tutorial')),
                ('buy_projects_video_url', models.URLField(max_length=251, verbose_name='video url')),
                ('complete_tasks_text_tutorial', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_text_tutorial_path, verbose_name='text_tutorial')),
                ('complete_tasks_screenshot_tutorial', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_screenshot_tutorial_path, verbose_name='text_tutorial')),
                ('complete_tasks_video_url', models.URLField(max_length=251, verbose_name='video url')),
                ('resubmit_wrong_answers_text_tutorial', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_text_tutorial_path, verbose_name='text_tutorial')),
                ('resubmit_wrong_answers_screenshot_tutorial', models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_screenshot_tutorial_path, verbose_name='text_tutorial')),
                ('resubmit_wrong_answers_video_url', models.URLField(max_length=251, verbose_name='video url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
