# Generated by Django 4.2.1 on 2023-09-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_cms_meta_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=2064)),
                ('answers', models.CharField(max_length=2064)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
