# Generated by Django 4.2.1 on 2023-09-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUSForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(max_length=64, verbose_name='firstName')),
                ('lastName', models.CharField(max_length=64, verbose_name='lastName')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('subject', models.CharField(max_length=128, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'ContactUS',
                'verbose_name_plural': 'ContactUS',
            },
        ),
    ]
