# Generated by Django 4.2.1 on 2023-09-20 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0005_contactusform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_form_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
