# Generated by Django 4.2.5 on 2023-10-06 12:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='meta_value',
            field=tinymce.models.HTMLField(),
        ),
    ]
