# Generated by Django 4.2.5 on 2023-10-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_remove_usermanual_project_task_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_task_1',
            field=models.CharField(default='How To Complete Task 1', max_length=32),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_task_10',
            field=models.CharField(default='How To Complete Task 10', max_length=32),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_task_11',
            field=models.CharField(default='How To Complete Task 11', max_length=32),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_task_2',
            field=models.CharField(default='How To Complete Task 2', max_length=32),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_task_3',
            field=models.CharField(default='How To Complete Task 3', max_length=32),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_task_4',
            field=models.CharField(default='How To Complete Task 4', max_length=32),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_task_5',
            field=models.CharField(default='How To Complete Task 5', max_length=32),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_task_6',
            field=models.CharField(default='How To Complete Task 6', max_length=32),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_task_7',
            field=models.CharField(default='How To Complete Task 7', max_length=32),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_task_8',
            field=models.CharField(default='How To Complete Task 8', max_length=32),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_task_9',
            field=models.CharField(default='How To Complete Task 9', max_length=32),
        ),
    ]
