# Generated by Django 4.2.5 on 2023-12-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_usermanual_how_to_complete_task_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCartInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('instructions', models.TextField(verbose_name='My Cart Instructions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
