# Generated by Django 4.2.5 on 2023-12-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_mycartinstructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answers',
            field=models.TextField(verbose_name='answers'),
        ),
    ]
