# Generated by Django 4.2.5 on 2024-02-07 13:57

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_faq_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_tasks_05_points',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.how_to_complete_tasks_user_manual, verbose_name='text_tutorial'),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_tasks_10_points',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.how_to_complete_tasks_user_manual, verbose_name='text_tutorial'),
        ),
        migrations.AddField(
            model_name='usermanual',
            name='how_to_complete_tasks_20_points',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.how_to_complete_tasks_user_manual, verbose_name='text_tutorial'),
        ),
    ]
