# Generated by Django 4.2.5 on 2024-02-15 06:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_usermanual_how_to_complete_tasks_05_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='whatsapp_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Whatspapp Mobile Number'),
        ),
    ]
