# Generated by Django 4.2.1 on 2023-08-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_discount_amount_order_gst_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='order number')),
                ('cgst_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='CGST percentage')),
                ('sgst_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='SGST number')),
                ('igst_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IGST number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
