# Generated by Django 4.2.1 on 2023-08-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderdetail_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='project_price',
        ),
    ]
