# Generated by Django 4.2.1 on 2023-08-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_order_number_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_of_payment',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10),
        ),
    ]
