# Generated by Django 4.2.1 on 2023-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_status_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_of_payment',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10),
        ),
    ]
