# Generated by Django 4.2.1 on 2023-08-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_status_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expire_on',
            field=models.DateTimeField(null=True, verbose_name='Expire on'),
        ),
    ]
