# Generated by Django 4.2.1 on 2023-08-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_expire_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expire_on',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_of_payment',
        ),
    ]
