# Generated by Django 4.2.1 on 2023-09-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_order_expire_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_of_payment',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10),
        ),
    ]
