# Generated by Django 4.2.1 on 2023-09-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_status_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Invoice number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_of_payment',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10, verbose_name='Status of payment'),
        ),
    ]
