# Generated by Django 4.2.5 on 2023-09-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_generated',
            field=models.BooleanField(default=False),
        ),
    ]
