# Generated by Django 4.2.5 on 2023-09-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_invoice_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_generated',
        ),
    ]
