# Generated by Django 4.2.5 on 2023-09-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_order_invoice_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment time'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_via',
            field=models.CharField(choices=[('online', 'Online')], default='online', max_length=30, verbose_name='Payment via'),
        ),
    ]
