# Generated by Django 4.2.5 on 2023-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_payment_time_order_payment_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CGST'),
        ),
        migrations.AddField(
            model_name='order',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IGST'),
        ),
        migrations.AddField(
            model_name='order',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SGST'),
        ),
    ]
