# Generated by Django 4.2.5 on 2023-10-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_cgst_order_igst_order_sgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_service_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax service fees'),
        ),
    ]
