# Generated by Django 4.2.5 on 2023-10-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_tax_service_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gst_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GST charges'),
        ),
    ]
