# Generated by Django 4.2.5 on 2023-11-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_gst_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='is complete'),
        ),
    ]
