# Generated by Django 4.2.5 on 2023-12-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_orderdetail_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_temp_order',
            field=models.BooleanField(default=False, verbose_name='is temp order?'),
        ),
    ]
