# Generated by Django 4.2.5 on 2023-12-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_order_is_temp_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_temp_order',
            field=models.BooleanField(default=True, verbose_name='is temp order?'),
        ),
    ]
