# Generated by Django 4.2.5 on 2023-12-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_order_is_temp_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='android_payload',
            field=models.TextField(blank=True, verbose_name='android_payload'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='transaction id'),
        ),
        migrations.AddField(
            model_name='order',
            name='webhook_payload',
            field=models.TextField(blank=True, verbose_name='webhook payload'),
        ),
    ]
