# Generated by Django 4.2.5 on 2024-01-05 06:41

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_orderdetail_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='report_file',
            field=models.FileField(null=True, upload_to=activityngo.utils.utils.get_activity_report_file_path, verbose_name='Report File'),
        ),
    ]
