# Generated by Django 4.2.5 on 2024-01-09 13:21

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_orderdetail_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='qr_code_verification',
            field=models.ImageField(blank=True, height_field='height_photo', null=True, upload_to=activityngo.utils.utils.get_student_qr_code_verification_filename, width_field='width_photo'),
        ),
    ]
