# Generated by Django 4.2.5 on 2024-01-09 13:45

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_orderdetail_qr_code_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='qr_code_verification',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_qr_code_verification_filename),
        ),
    ]
