# Generated by Django 4.2.5 on 2024-01-10 10:08

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_orderdetail_qr_code_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_certificate_file',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_activity_certificate_file_filename),
        ),
    ]
