# Generated by Django 4.2.5 on 2024-01-16 06:07

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_alter_orderdetail_student_activity_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_chapters',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_activity_chapters_file_filename),
        ),
    ]
