# Generated by Django 4.2.5 on 2024-01-17 05:36

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_orderdetail_student_activity_pie_chart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='student_activity_pie_chart',
            new_name='student_activity_pie_chart_4',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_5',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
    ]
