# Generated by Django 4.2.5 on 2024-01-17 05:38

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_rename_student_activity_pie_chart_orderdetail_student_activity_pie_chart_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_10',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_11',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_12',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_13',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_14',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_15',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_16',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_17',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_18',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_19',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_20',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_21',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_6',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_7',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_8',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_pie_chart_9',
            field=models.ImageField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_pie_chart_filename),
        ),
    ]
