# Generated by Django 4.2.5 on 2024-01-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_remove_orderdetail_student_activity_pie_chart_21'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_webhook_call',
            field=models.BooleanField(default=False, verbose_name='is webhook call'),
        ),
    ]
