# Generated by Django 4.2.5 on 2024-01-23 04:53

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_order_is_webhook_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_task_4',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_activity_chapters_file_filename),
        ),
    ]
