# Generated by Django 4.2.5 on 2024-01-29 08:05

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_orderdetail_student_activity_task_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_task_9_2_10',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_activity_chapters_file_filename),
        ),
    ]
