# Generated by Django 4.2.5 on 2024-01-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_orderdetail_student_activity_task_9_2_10'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='student_activity_task_9_2_10',
            new_name='student_activity_task_9',
        ),
    ]
