# Generated by Django 4.2.5 on 2024-01-29 12:44

import activityngo.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_rename_student_activity_task_9_2_10_orderdetail_student_activity_task_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='student_activity_task_2_and_10',
            field=models.FileField(blank=True, null=True, upload_to=activityngo.utils.utils.get_student_activity_chapters_file_filename),
        ),
    ]
