# Generated by Django 4.2.5 on 2024-02-08 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0014_discount_state'),
        ('order', '0048_orderdetail_student_activity_short_report_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_discount_code', to='discount.discount'),
        ),
    ]
