# Generated by Django 4.2.5 on 2024-02-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_orderdetail_activity_completed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='activity_completed_date',
        ),
    ]
