# Generated by Django 4.2.5 on 2024-02-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_alter_implementationbatches_unique_together'),
        ('order', '0052_alter_orderdetail_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='activity_completed_date',
            field=models.DateTimeField(null=True, verbose_name='Activity subscribed date'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='implementation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.implementationbatches'),
        ),
    ]
