# Generated by Django 4.2.5 on 2024-02-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_orderdetail_activity_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='number_of_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of days'),
        ),
    ]
