# Generated by Django 4.2.5 on 2024-04-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_orderdetail_activity_completed_date_by_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_gateway_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payment Gateway Fee'),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sub Total amount'),
        ),
    ]
