# Generated by Django 4.2.1 on 2023-08-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='login_type',
            field=models.CharField(choices=[('S', 'Simple'), ('A', 'Apple'), ('F', 'Facebook'), ('G', 'Google')], default='S', max_length=2, verbose_name='Login Type'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='social_key',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Social Key'),
        ),
    ]
