# Generated by Django 4.2.1 on 2023-08-16 10:18

import activityngo.utils.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_applicationuser_login_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walkthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Walkthrough',
                'verbose_name_plural': 'Walkthrough',
            },
        ),
        migrations.CreateModel(
            name='WalkthroughMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, height_field='height_photo', null=True, upload_to=activityngo.utils.utils.get_walkthrought_random_filename, width_field='width_photo')),
                ('width_photo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_photo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('walkthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkthrough_media', to='custom_auth.walkthrough')),
            ],
            options={
                'verbose_name': 'Walkthrough Media',
                'verbose_name_plural': 'Walkthrough Medias',
            },
        ),
    ]
