# Generated by Django 4.2.1 on 2023-08-23 04:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_walkthrough_walkthroughmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkthroughSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('meta_value', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
