# Generated by Django 4.2.1 on 2023-09-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('admin', 'Admin'), ('sub_admin', 'Sub Admin'), ('ngo', 'NGO'), ('college', 'College')], default='admin', max_length=16, null=True, verbose_name='User Type'),
        ),
    ]
