# Generated by Django 4.2.5 on 2023-10-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0011_alter_applicationuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Device Id'),
        ),
    ]
